class Loc:
    title = '//android.widget.TextView[@text="CHECKOUT: OVERVIEW"]'
    product_name = ''
    product_price = ''
    total_price = '//android.widget.TextView[@text="Item total: $39.98"]'
    tax = '//android.widget.TextView[@text="Tax: $3.20"]'
    total = '//android.widget.TextView[@text="Total: $43.18"]'
    button_cancel = ''
    button_finish = ''
    co_product1 = '//android.widget.TextView[@text="$29.99"]'
    co_product2 = '//android.widget.TextView[@text="$9.99"]'
